import React from 'react';

export const Repositories: RepositoryDef[] = [
    {
        key: 1,
        belongsTo: "Maxim",
        title: "Test1",
        createdOn: "2022-02-18",
        currentWealth: 10000000,
    },
    {
        key: 2,
        belongsTo: "Hohn03",
        title: "Test2",
        createdOn: "2022-02-18",
        currentWealth: 1034000,
    },
    {
        key: 3,
        belongsTo: "Dimitrij",
        title: "Test3",
        createdOn: "2022-02-18",
        currentWealth: 0.5,
    },
    {   key: 4,
        belongsTo: "Maxim",
        title: "Test4",
        createdOn: "2022-02-18",
        currentWealth: 153134,
    },
    {
        key: 5,
        belongsTo: "Maxim",
        title: "Test5",
        createdOn: "2022-02-18",
        currentWealth: 2452,
    },
    {
        key: 6,
        belongsTo: "Maxim",
        title: "Test1",
        createdOn: "2022-02-18",
        currentWealth: 10000000,
    },
    {
        key: 7,
        belongsTo: "Hohn03",
        title: "Test2",
        createdOn: "2022-02-18",
        currentWealth: 1034000,
    },
    {
        key: 8,
        belongsTo: "Dimitrij",
        title: "Test3",
        createdOn: "2022-02-18",
        currentWealth: 0.5,
    },
    {   key: 9,
        belongsTo: "Maxim",
        title: "Test4",
        createdOn: "2022-02-18",
        currentWealth: 153134,
    },
    {
        key: 10,
        belongsTo: "Maxim",
        title: "Test5",
        createdOn: "2022-02-18",
        currentWealth: 2452,
    },
    {
        key: 11,
        belongsTo: "Maxim",
        title: "Test1",
        createdOn: "2022-02-18",
        currentWealth: 10000000,
    },
    {
        key: 12,
        belongsTo: "Hohn03",
        title: "Test2",
        createdOn: "2022-02-18",
        currentWealth: 1034000,
    },
    {
        key: 13,
        belongsTo: "Dimitrij",
        title: "Test3",
        createdOn: "2022-02-18",
        currentWealth: 0.5,
    },
    {   key: 14,
        belongsTo: "Maxim",
        title: "Test4",
        createdOn: "2022-02-18",
        currentWealth: 153134,
    },
    {
        key: 15,
        belongsTo: "Maxim",
        title: "Test5",
        createdOn: "2022-02-18",
        currentWealth: 2452,
    },
];

export type RepositoryDef = {
    key: number,
    belongsTo: string,
    title: string,
    createdOn: string,
    currentWealth: number,
    visible?: boolean,
    //changes?: [],
}